VG_POS_FAMILIES = {
    0 : "Ninguna",
    1 : "Alimentos",
    2 : "Bebidas",
    4 : "Recetas Alimentos",
    5 : "Recetas Bebidas",
    6 : "Cigarros",
    7 : "Lacteos",
    8 : "Hielo",
    9 : "Souvenirs",
    10 : "Tabacos",
    11 : "Frutas y Verduras",
    12 : "Botanas",
    13 : "Abarrotes",
    14 : "Medicina",
    15 : "Limpieza",
    16 : "Carnes y Leche",
    17 : "Revistas",
    18 : "Lavanderia",
    19 : "Cervezas",
    20 : "Refrescos y Jugos",
    21 : "Vinos y Licores",
    22 : "Tequilas y Mezcales",
    23 : "Whiskys y Ginebra",
    24 : "Estampillas",
    25 : "Tarjetas Telefonicas",
    26 : "Otros",
    27 : "Cafes y Tes",
    28 : "Boutique",
    29 : "Desechables",
    30 : "Ceramica",
    31 : "Farmacia",
    32 : "Suministros",
    33 : "Art.Fotograficos",
    34 : "Hielo y Agua",
    35 : "Perfumeria",
    36 : "Salchichoneria",
    37 : "Dulces",
    38 : "Congelados",
    39 : "Carnes y Salchichoneria",
    40 : "Jugueteria",
    41 : "Alimentos Congelados",
    42 : "Cremas",
    43 : "Compras Directas de Mercancia Varios",
    44 : "Faldas",
    45 : "Recepcion",
    46 : "Suministros",
    47 : "Dulces",
    48 : "Taller de Mantenimiento",
    49 : "Electrico",
    50 : "Mariscos",
    51 : "Papeleria",
    52 : "Cristaleria",
    53 : "Masajes",
    54 : "Faciales",
    55 : "Salon de Belleza",
    56 : "Tratamientos",
    57 : "Aguas",
    58 : "Vodka y Ron",
    59 : "Billete Americano",
    60 : "Documento Americano",
    61 : "Billete Canadiense",
    62 : "Documento Canadiense",
    63 : "Moneda Nacional",
    64 : "Inflables",
    65 : "Ropa de Playa",
    66 : "Accesorios P/Ropa",
    67 : "Articulos de playa",
    68 : "Carnes frias",
    69 : "Nieves y Helados",
    70 : "Articulos de belleza",
    71 : "Jabones y Shampoo",
    72 : "Leche",
    73 : "Agua importación",
    74 : "Ultramarinos",
    75 : "Abarrotes importación",
    76 : "Juguetes madera",
    77 : "Bronceadores",
    78 : "Prepago SPA",
    79 : "Espigon",
    80 : "Promotores",
    81 : "Preventa",
    82 : "Vidrio Soplado",
    83 : "Talavera",
    84 : "Conchas",
    85 : "Pewters",
    86 : "Articulos Villa del Palmar",
    87 : "Laton",
    88 : "Artesanias en General",
    89 : "Fotografia",
    90 : "Servicios Promotores",
    91 : "Suplemento Meal Plan",
    92 : "Membresias",
    93 : "Bodas y Banquetes",
    94 : "Cuadros",
    95 : "Artesanias de Madera",
    96 : "Lavanderia Automatica",
    97 : "Parrillada",
    98 : "Fiesta Mexicana",
    99 : "Beach Party",
    100	: "Higiene Personal",
    101	: "Artesanias de Hueso",
    102	: "Artesanias de Piedra",
    103	: "Lavanderia Domestica",
    104	: "Articulos para Regalo",
    105	: "Articulos Bebe",
    106	: "Canastas Promocion Market",
    107	: "Photo Shop",
    108	: "Pan Elaborado",
    109	: "Tenis",
    110	: "Cyber Palmita",
    111	: "Boletos Comedor",
    112	: "Consignación",
    113	: "Miscelaneos",
    114	: "Kid Club",
    115	: "Puros",
    116	: "Lentes y accesorios",
    117	: "Hieleras",
    118	: "Higiene bebe",
    119	: "Libros",
    120	: "Postales y estampillas",
    121	: "Vinos espumosos",
    123	: "Whiskies",
    124	: "Cogñacs",
    125	: "Vodkas",
    126	: "Ginebras",
    127	: "Tequilas",
    128	: "Rones",
    129	: "Brandys",
    130	: "Licores",
    131	: "Mezcales",
    132	: "Refrescos",
    133	: "Malteadas",
    134	: "Bebidas de cocteles",
    135	: "Bebidas energeticos",
    136	: "Frutas",
    137	: "Verduras",
    138	: "Embutidos",
    139	: "Huevos",
    140	: "Mermeladas",
    141	: "Azucar",
    142	: "Miel",
    143	: "Galletas",
    144	: "Sopas",
    145	: "Panes",
    146	: "Tortillas",
    147	: "Cereales",
    148	: "Mantequilla",
    149	: "Condimentos y especies",
    150	: "Te",
    151	: "Cafe",
    152	: "Salsas",
    153	: "Sal",
    154	: "Jugos y nectares",
    155	: "Concentrados",
    156	: "Semillas granos y secos",
    157	: "Frutas en almibar y conservas",
    158	: "Aceites comestibles",
    159	: "Quesos",
    160	: "Chocolates",
    161	: "Aderezos",
    162	: "Mayonesas y mostazas",
    163	: "Vestidos",
    164	: "Viseras gorras y sombreros",
    165	: "Sourvenirs y recuerdos",
    166	: "Bronceadores",
    167	: "Artesanias barro y ceramicas",
    168	: "Vinos consignacion",
    169	: "Limpieza en general",
    170	: "Camisas",
    171	: "Alimentos",
    172	: "Bodas alimentos",
    173	: "Bodas bebidas",
    174	: "Suministros A Y B",
    175	: "Miscelaneos",
    179	: "Consignacion",
    180	: "Reposteria",
    181	: "Carnes",
    182	: "Vinos blancos",
    183	: "Vinos tintos",
    184	: "Nieves y helados",
    186	: "Chamarras",
    187	: "Accesorios para cabello",
    188	: "Esmalte para uñas",
    189	: "Jarabes",
}

MARKET_CONSUMPTION_CENTER_ID = 8
